common: &common_settings
  adapter: postgresql
  encoding: unicode
  min_messages: warning
  pool: 5
  username: postgres
  password: postgres
  host: localhost
  port: 5432

development:
  <<: *common_settings
  database: convo_development

test: &test
  <<: *common_settings
  database: convo_test

production:
  <<: *common_settings
  database: convo_production

cucumber:
  <<: *test