#common: &common_settings

development:
  adapter: sqlite3
  database: db/convo_development.sqlite3
  pool: 5
  timeout: 5000

test: &test
#  <<: *common_settings
  database: convo_test

production:
  adapter: postgresql
  encoding: unicode
  min_messages: warning
  pool: 5
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  database: convo_production

cucumber:
  <<: *test
